version: '2'

services:
  # characters:
  #   container_name: characters
  #   build: 
  #     context: .
  #     dockerfile: ./apps/characters/Dockerfile
  #     target: development
  #   command: npm run start:dev characters
  #   env_file:
  #     - ./apps/characters/.env 
  #   depends_on:
  #     - mongo-db
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules 
  #   ports:
  #     - '3001:3001'
  #   restart: unless-stopped
  mongo-db:
    container_name: mongo-db
    image: mongo
    hostname: mongodb
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGO_INITDB_USERNAME: ${MONGODB_DB_USER}
      MONGO_INITDB_PASSWORD: ${MONGODB_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DB_DATABASE}
    ports:
      - ${MONGODB_PORT}:27017
    volumes:
      - ./db/mongodb/data/db/:/data/db/
      - ./db/mongodb/data/log/:/var/log/mongodb/ 